"""Term catalog of the pair chart: every visible string lives here under a semantic key, one
catalog per language. Values are str.format templates; the chart code only asks for keys."""

from __future__ import annotations

_RU = {
    "panel.vision": "ЗРЕНИЕ — укладка озвучки на референс (отклонение от масштаба, кадры)",
    "panel.audio": "СЛУХ — остаток после доводки (кадры)",
    "axis.time": "время референса, с",
    "axis.time.mmss": "мм:сс",
    "axis.vision_y": "Δ укладки, кадры",
    "axis.audio_y": "Δ остатка, кадры",
    "colorbar.cos": "похожесть кадра",
    "colorbar.w": "уверенность слуха",
    "legend.anchor_vision": "якорь зрения (цвет — похожесть кадра)",
    "legend.anchor_audio": "якорь слуха (цвет — уверенность)",
    "legend.layout": "укладка (где лежит озвучка)",
    "legend.audio_curve": "кривая доводки",
    "zone.vision_cut": "нет кадров озвучки",
    "zone.video_freeze": "кадр озвучки не меняется",
    "zone.audio_gap": "нет звука озвучки",
    "zone.dtw_cut": "вырез звука (DTW)",
    "event.vision_step": "ступень укладки {value:+.1f} с",
    "event.audio_cut": "рез слуха {value:+.0f} мс",
    "event.audio_jump": "скачок структуры звука {value:+.1f} с",
    "event.dtw_insert": "вставка звука +{value:.0f} с",
    "legend.vision_step": "ступень укладки",
    "legend.audio_cut": "рез слуха",
    "legend.audio_jump": "скачок структуры звука",
    "legend.dtw_insert": "вставка звука (DTW)",
    "segment.speed": "скорость {value:+.2f} %",
    "anchors_clipped": "↑ {value} якорей вне оси",
    "header.vision": "зрение",
    "header.audio": "слух",
    "metric.assigned": "назначено {value:.1f} %",
    "metric.cos": "похожесть {value:.2f}",
    "metric.scale": "масштаб {value:+.2f} %",
    "metric.telecine": "телесин реф/озв {value}",
    "metric.tc_dropped": "прорежено {value} к",
    "metric.geom": "геометрия {value}",
    "metric.mirror": "зеркало {value}",
    "metric.container_delay": "задержка контейнера {value:+.3f} с",
    "metric.vision_cuts": "вырезов {value}",
    "metric.freezes": "заморозок {value}",
    "metric.method": "метод {value}",
    "metric.structure": "структура звука {value}",
    "metric.resid": "остаток {value:.1f} мс",
    "metric.cuts": "резов {value}",
    "metric.max_step": "макс. рез {value:.0f} мс",
    "metric.coverage": "опора {value:.0f} %",
    "metric.excess": "погашенный ход {value:.1f} с",
    "metric.filled": "залито референсом {value:.0f} с",
    "metric.av_offset": "сдвиг до доводки {value}",
    "metric.verdict": "вердикт {value}",
    "verdict.ok": "норма",
    "verdict.warn": "предупреждение",
    "verdict.critical": "критично",
    "value.none": "—",
    "value.yes": "да",
    "value.no": "нет",
    "value.count_dur": "{n} / {dur:.0f} с",
    "value.telecine": "{ref:.2f} / {dub:.2f}",
    "value.geom": "×{sx:.3f}/{sy:.3f}, якорей {n}",
    "value.structure": "плато {plateaus}, скачков {jumps}",
    "value.av_offset": "{lag:+.0f} ± {mad:.0f} мс",
}

_EN = {
    "panel.vision": "VISION — dub layout on the reference (deviation from scale, frames)",
    "panel.audio": "HEARING — residual after refinement (frames)",
    "axis.time": "reference time, s",
    "axis.time.mmss": "mm:ss",
    "axis.vision_y": "Δ layout, frames",
    "axis.audio_y": "Δ residual, frames",
    "colorbar.cos": "frame similarity",
    "colorbar.w": "hearing confidence",
    "legend.anchor_vision": "vision anchor (colour — frame similarity)",
    "legend.anchor_audio": "hearing anchor (colour — confidence)",
    "legend.layout": "layout (where the dub lies)",
    "legend.audio_curve": "refinement curve",
    "zone.vision_cut": "no dub frames",
    "zone.video_freeze": "dub frame does not change",
    "zone.audio_gap": "no dub sound",
    "zone.dtw_cut": "sound cut (DTW)",
    "event.vision_step": "layout step {value:+.1f} s",
    "event.audio_cut": "hearing cut {value:+.0f} ms",
    "event.audio_jump": "sound structure jump {value:+.1f} s",
    "event.dtw_insert": "sound insert +{value:.0f} s",
    "legend.vision_step": "layout step",
    "legend.audio_cut": "hearing cut",
    "legend.audio_jump": "sound structure jump",
    "legend.dtw_insert": "sound insert (DTW)",
    "segment.speed": "speed {value:+.2f} %",
    "anchors_clipped": "↑ {value} anchors off axis",
    "header.vision": "vision",
    "header.audio": "hearing",
    "metric.assigned": "assigned {value:.1f} %",
    "metric.cos": "similarity {value:.2f}",
    "metric.scale": "scale {value:+.2f} %",
    "metric.telecine": "telecine ref/dub {value}",
    "metric.tc_dropped": "thinned {value} fr",
    "metric.geom": "geometry {value}",
    "metric.mirror": "mirror {value}",
    "metric.container_delay": "container delay {value:+.3f} s",
    "metric.vision_cuts": "cuts {value}",
    "metric.freezes": "freezes {value}",
    "metric.method": "method {value}",
    "metric.structure": "sound structure {value}",
    "metric.resid": "residual {value:.1f} ms",
    "metric.cuts": "cuts {value}",
    "metric.max_step": "max cut {value:.0f} ms",
    "metric.coverage": "support {value:.0f} %",
    "metric.excess": "cancelled movement {value:.1f} s",
    "metric.filled": "filled from reference {value:.0f} s",
    "metric.av_offset": "offset before refinement {value}",
    "metric.verdict": "verdict {value}",
    "verdict.ok": "ok",
    "verdict.warn": "warning",
    "verdict.critical": "critical",
    "value.none": "—",
    "value.yes": "yes",
    "value.no": "no",
    "value.count_dur": "{n} / {dur:.0f} s",
    "value.telecine": "{ref:.2f} / {dub:.2f}",
    "value.geom": "×{sx:.3f}/{sy:.3f}, anchors {n}",
    "value.structure": "plateaus {plateaus}, jumps {jumps}",
    "value.av_offset": "{lag:+.0f} ± {mad:.0f} ms",
}

CATALOGS = {"ru": _RU, "en": _EN}
DEFAULT_LANG = "ru"


def term(key: str, lang: str = DEFAULT_LANG, **fmt) -> str:
    """Formatted text for `key` in `lang`; an unknown key returns the key itself so a chart never
    fails on a missing translation."""
    cat = CATALOGS.get(lang) or CATALOGS[DEFAULT_LANG]
    tpl = cat.get(key) or CATALOGS[DEFAULT_LANG].get(key) or key
    try:
        return tpl.format(**fmt) if fmt else tpl
    except (KeyError, ValueError, IndexError):
        return tpl
